apiVersion: v1
kind: Pod
metadata:
  name: hz-client
spec:
  containers:
  - name: hz-client
    image: maven:3-jdk-8-slim
    ports:
    - containerPort: 5701
    envFrom:
    - configMapRef:
        name: hz-config