apiVersion: v1
kind: Service
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  type: NodePort
  selector:
    app: hazelcast
  ports:
  - protocol: TCP
    port: 5701
    name: hzport

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: hazelcast
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
      - name: hazelcast-node
#      below image definitions are used in pipeline
#      todo find proper parameter passing
        image: hz-k8s:3.9
        ports:
        - containerPort: 5701
        envFrom:
        - configMapRef:
            name: hz-config