apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: hz-deployment
  labels:
    app: hz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hz
  template:
    metadata:
      labels:
        app: hz
    spec:
      containers:
      - name: hz
        image: hazelcast/hazelcast-openshift:3.8.6
        ports:
        - containerPort: 5701
        env:
        - name: HAZELCAST_KUBERNETES_SERVICE_NAME
          value: "hz"
        - name: HAZELCAST_KUBERNETES_NAMESPACE
          value: "default"